---
title: "Project Report"
author: "Elaina Passero"
date: "October 29, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(dplyr)
library(readr)
library(stars)
```

# Probability of Occurrence of Riparian Vegetation Guilds by Flow Scenario

## Initialize variables
```{r inputs, message=FALSE}
# This is where users will put in the % flow reduction, withdrawal, median enforcement, or specify a scenario like flow reduction with climate change

enforce_med <- "No"
per_red <- 0.20 # percent flow reduction set to 0 if adding withdrawal
median_q <- 160 # median flow value - could use monthly or annual
withdrawal <- 0 # set to 0 if doing percent flow reduction
guild_list <- list("guild1", "guild2", "guild3")

# read in historical flow record
historic_q <- readr::read_csv("Cherry_Braid_hydrograph.csv",col_names = TRUE)
ep_zone_pref <- readr::read_csv("guild_by_ep.csv",col_names = TRUE)
inun_q_map <- read_stars("inunQmap.tif")
```

## Build Flow Scenario
```{r flow_scene}
# want to have a baseline "historic" scenario to compare to the scenarios the script generates
source("flow.scenario.R")
flow_scene <- flow.scenario(historic_q,enforce_med,median_q,withdrawal,per_red)

```

## Calculate EP for Flow Scenario
```{r calc_ep}
source("q.ep.weibull.R")
hydro_ep <- q.ep.weibull()

```

## Reclassify inundating Q map to EP
```{r inunq_to_ep}

```

## Reclassify EP map to Prob(Veg) map
```{r ep_to_probveg}
# Each scenario creates a list of raster layers
# Each object in list is a guild

```

## Compare Prob(Veg) maps for multiple scenarios
```{r compare_probs}
# Stack or brick all of the rasters for the same guilds
# layerStats in raster
# identify areas/features most sensitive to change - difference in rasters
# Identify the scenarios with highest probs


```

